import { Controller, Logger, Post, UseFilters, UseGuards, Headers, HttpCode, HttpStatus, Body, Query, Get, UseInterceptors, Param } from '@nestjs/common';
import { CompanyService } from './company.service';
import { ApiBadRequestResponse, ApiHeader, ApiInternalServerErrorResponse, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { HttpExceptionFilter } from '../filter/http-exception.filter';
import { UtilsService } from '../utils/utils.service';
import { AuthGuard } from '../authentication/guard/auth.guard';
import { CompanyDTO } from './dtos/company.dto';
import { FindQueryOptions, QueryParamsCompany } from '../constants/common';
import { VerifyPaginationInterceptor } from '../interceptor/verify-pagination.interceptor';
import { VerifyCompanyParamsInterceptor } from '../interceptor/verify-company-params.interceptor';

@ApiTags('Company')
@Controller('company')
@UseGuards(AuthGuard)
@UseFilters(HttpExceptionFilter)
export class CompanyController {
  private logger = new Logger(CompanyController.name);
  constructor(private service: CompanyService, private utilsService: UtilsService) {}
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Create a new Company ' })
  @ApiInternalServerErrorResponse()
  @ApiBadRequestResponse()
  @ApiUnauthorizedResponse()
  @ApiResponse({
    status: HttpStatus.NO_CONTENT,
    description: 'The Company has been successfully created.'
  })
  @ApiHeader({
    name: 'unique-trace-id',
    description: 'Autogenerated trace id',
    required: false
  })
  @ApiHeader({
    name: 'app_key',
    description: 'App Secret',
    required: true
  })
  @Post('/')
  async create(@Body() dto: CompanyDTO, @Headers('unique-trace-id') uniqueTraceId: string): Promise<any> {
    this.logger.log({
      level: 'info',
      message: 'Trying to create new Company ',
      method: this.create.name,
      'unique-trace-id': uniqueTraceId
    });
    await this.service.create(dto);
  }

  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Find All Companies ' })
  @ApiInternalServerErrorResponse()
  @ApiBadRequestResponse()
  @ApiUnauthorizedResponse()
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'The Companies have been found successfully.'
  })
  @ApiHeader({
    name: 'unique-trace-id',
    description: 'Autogenerated trace id',
    required: false
  })
  @ApiHeader({
    name: 'app_key',
    description: 'App Secret',
    required: true
  })
  @ApiQuery({
    name: 'skip',
    type: 'number',
    required: false,
    description: 'Number of Company rows to be skipped '
  })
  @ApiQuery({
    name: 'size',
    type: 'number',
    required: false,
    description: 'Number of Company rows to be returned '
  })
  @ApiQuery({
    name: 'createDateSince',
    type: 'string',
    required: false,
    description: 'Creation date where start to find '
  })
  @ApiQuery({
    name: 'createDateTo',
    type: 'string',
    required: false,
    description: 'Creation date up to find '
  })
  @Get('/')
  @UseInterceptors(VerifyPaginationInterceptor, VerifyCompanyParamsInterceptor)
  async get(@Headers('unique-trace-id') uniqueTraceId: string, @Query() params?: QueryParamsCompany) {
    this.logger.log({
      level: 'info',
      message: 'Trying to find Companies ',
      method: this.get.name,
      'unique-trace-id': uniqueTraceId
    });
    const options: FindQueryOptions = this.utilsService.buildOptions(params);
    return await this.service.findAll(options);
  }

  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Find All Companies ' })
  @ApiInternalServerErrorResponse()
  @ApiBadRequestResponse()
  @ApiUnauthorizedResponse()
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'The Companies have been found successfully.'
  })
  @ApiHeader({
    name: 'unique-trace-id',
    description: 'Autogenerated trace id',
    required: false
  })
  @ApiHeader({
    name: 'app_key',
    description: 'App Secret',
    required: true
  })
  @ApiQuery({
    name: 'skip',
    type: 'number',
    required: false,
    description: 'Number of Company rows to be skipped '
  })
  @ApiQuery({
    name: 'size',
    type: 'number',
    required: false,
    description: 'Number of Company rows to be returned '
  })
  @ApiQuery({
    name: 'transferDateSince',
    type: 'string',
    required: false,
    description: 'Transfer date where start to find '
  })
  @ApiQuery({
    name: 'transferDateTo',
    type: 'string',
    required: false,
    description: 'Transfer date up to find '
  })
  @Get('/transactions')
  @UseInterceptors(VerifyPaginationInterceptor)
  async getByTransactions(@Headers('unique-trace-id') uniqueTraceId: string, @Query() params?: QueryParamsCompany) {
    this.logger.log({
      level: 'info',
      message: 'Trying to find Companies filtering by transfer date of transactions',
      method: this.get.name,
      'unique-trace-id': uniqueTraceId
    });
    const options: FindQueryOptions = this.utilsService.buildOptions(params);
    return await this.service.findAllByTransactions(options);
  }

  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Find a Company by Id ' })
  @ApiInternalServerErrorResponse()
  @ApiUnauthorizedResponse()
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'The Company has been found successfully.'
  })
  @ApiHeader({
    name: 'unique-trace-id',
    description: 'Autogenerated trace id',
    required: false
  })
  @ApiHeader({
    name: 'app_key',
    description: 'App Secret',
    required: true
  })
  @ApiParam({
    name: 'id',
    description: 'Company id ',
    required: true
  })
  @Get('/:id')
  async getById(@Headers('unique-trace-id') uniqueTraceId: string, @Param('id') id: number) {
    this.logger.log({
      level: 'info',
      message: `Trying to find a company for this id: ${id}`,
      method: this.getById.name,
      'unique-trace-id': uniqueTraceId
    });
    return await this.service.findById(id);
  }
}
